name: MATSYA
on: 
 push:
    branches:
    - main
 pull_request:
    branches:
    - main 
  

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      - name:  Arduino-cli Setup
        uses: arduino/setup-arduino-cli@v1

      - name: config 
        run: arduino-cli config init
        
      - name: updating core 
        run: |
          arduino-cli core update-index -v
          arduino-cli config add board_manager.additional_urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli config set library.enable_unsafe_install true
          arduino-cli core search esp8266 -v
          arduino-cli core install esp8266:esp8266@2.7.4
     
        
      - name: Library install
        run: |
          arduino-cli lib install  --git-url https://github.com/jfturcot/SimpleTimer.git
          arduino-cli lib install NTPClient
          arduino-cli lib install PubSubClient
          arduino-cli lib install ArduinoJson
          arduino-cli lib install OneWire
          arduino-cli lib install DallasTemperature
               
        # compilation of file 
      - name: compilation of ino file
        run: arduino-cli compile -b esp8266:esp8266:nodemcu ./MATSYA_FW_Release_1 
  
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      - name:  Arduino-cli Setup
        uses: arduino/setup-arduino-cli@v1

      - name: config 
        run: arduino-cli config init
        
      - name: updating core 
        run: |
          arduino-cli core update-index -v
          arduino-cli config add board_manager.additional_urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli config set library.enable_unsafe_install true
          arduino-cli core search esp8266 -v
          arduino-cli core install esp8266:esp8266@2.7.4
     
        
      - name: Library install
        run: |
          arduino-cli lib install  --git-url https://github.com/jfturcot/SimpleTimer.git
          arduino-cli lib install NTPClient
          arduino-cli lib install PubSubClient
          arduino-cli lib install ArduinoJson
          arduino-cli lib install OneWire
          arduino-cli lib install DallasTemperature
               
        # compilation of file
     
      
      - name: compilation of ino file
       
        run: arduino-cli compile -b esp8266:esp8266:nodemcu ./MATSYA_FW_Release_1  --build-path MATSYA_FW/MATSYA_FW_Release_1  
      - name: Creating timestamp folder  
        run: | 
           mkdir date
           tar -czvf date/$(date +"%d-%m-%Y").tar MATSYA_FW/MATSYA_FW_Release_1/MATSYA_FW_Release_1.ino.bin
      
      - name: Upload README.md to Google Drive
        uses: Jodebu/upload-to-drive@v1
        with:
          target: "date"
          credentials: ${{ secrets.DEPLOYE }}
          folder: 1apDvCcHCbu8Jm_wD01uRN5SwbhpsC7v3
   




